### Ajustes Seguridad
# ¡¡¡CAMBIAR EL PIN POR DEFECTO (991199)!!!
PinCode: 991199

### Ajustes Idiomas
# Para ver los idiomas aceptados acceder a https://github.com/EuskadiTech/LocalAxel-OTA
LANG: "ES"

### Ajustes Actualizaciones (OTA)
# Si quieres desactivar los cambios, NO TOQUES ESTO, Cambia OTA_Disable
# Solo hazlo una vez instalado
OTA_URL_Prefix: "https://euskaditech-ota.netlify.app/OTA/LocalAxel/ES/{}"
OTA_Disable: False

### Menu Comedor
# Solicita el menu del comedor desde https://tech.eus/axis/link/localaxel/solicitar_comedor.html
Menu_URL: "https://euskaditech-ota.netlify.app/OTA/Comedor/test.json"
Menu_Disable: False
